// Code generated by mockery v2.20.2. DO NOT EDIT.

package mockStoreGrpc

import (
	entities "github.com/Nikkoz/mp.gateway/internal/entities"
	context "github.com/Nikkoz/mp.gateway/pkg/types/context"

	mock "github.com/stretchr/testify/mock"

	store "github.com/Nikkoz/mp.gateway/internal/domain/store"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1, access
func (_m *Store) Create(ctx context.Context, _a1 *store.Store, access *entities.Access) (uint, error) {
	ret := _m.Called(ctx, _a1, access)

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *store.Store, *entities.Access) (uint, error)); ok {
		return rf(ctx, _a1, access)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *store.Store, *entities.Access) uint); ok {
		r0 = rf(ctx, _a1, access)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *store.Store, *entities.Access) error); ok {
		r1 = rf(ctx, _a1, access)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStore(t mockConstructorTestingTNewStore) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
